name: actions-s3-cache
author: shonansurvivors
description: This action installs dependencies or builds, and caches them in S3.
inputs:
  s3-bucket:
    required: true
  cache-key:
    required: true
  paths:
    required: true
  command:
    required: true
  working-directory:
    required: false
    default: ./
runs:
  using: node12
  main: dist/index.js
branding:
  icon: package
  color: yellow
